// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  fullWidth: string;
  smallSize: string;
  yellow: string;
}
export const cssExports: CssExports;
export default cssExports;
