// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'homePage': string;
  'homePageInfo': string;
  'homePageParallaxWrapper': string;
  'homePageWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
