// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headerLogo': string;
  'headerMenu': string;
  'headerMenuLink': string;
  'headerMenuLinkActive': string;
  'headerWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
