// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__logo': string;
  'header__menu': string;
  'header__menuLink': string;
  'header__menuLinkActive': string;
  'header__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
