// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer__info': string;
  'footer__infoLink': string;
  'footer__wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
